function PlotSpeeds(t, Vcggs)

    % [m/s] Eastern Speed
    VE = Vcggs(1, :) * 1000;

    % [m/s] Northern Speed
    VN = Vcggs(2, :) * 1000;

    % [m/s] Zenith Speed
    VZ = Vcggs(3, :) * 1000;

    % [m/s] Total Speed
    VTotal = sqrt(VE.^2 + VN.^2 + VZ.^2);

    % [] Initiates a New Window and Adjusts Its Properties
    Window = figure( ...
                'Color', 'w',...
                'Name', 'Speed Analysis', ...
                'NumberTitle', 'Off');

    %% Subplot 1: Eastern Speed vs. Time

    % [] Adds First Subplot
    Axes1 = subplot(2, 2, 1, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [0, 500], ...
            'Xtick', 0:7:70, ...
            'Ytick', 0:50:500);

    % [] Adds a Title to the First Subplot
    title('East', 'FontSize', 16, 'Parent', Axes1);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes1);

    % [] Adds a Label to the Y Axis
    ylabel('Speed (m/s)', 'FontSize', 12, 'Parent', Axes1);

    % [] Adds a Plot to the First Subplot
    plot(t, VE, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes1);

    %% Subplot 2: Northern Speed vs. Time

    % [] Adds Second Subplot
    Axes2 = subplot(2, 2, 2, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [-150, 0], ...
            'Xtick', 0:7:70, ...
            'Ytick', -150:15:0);

    % [] Adds a Title to the Second Subplot
    title('North', 'FontSize', 16, 'Parent', Axes2);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes2);

    % [] Adds a Label to the Y Axis
    ylabel('Speed (m/s)', 'FontSize', 12, 'Parent', Axes2);

    % [] Adds a Plot to the Second Subplot
    plot(t, VN, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes2);

    %% Subplot 3: Zenith Speed vs. Time

    % [] Adds Third Subplot
    Axes3 = subplot(2, 2, 3, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [-200, 800], ...
            'Xtick', 0:7:70, ...
            'Ytick', -200:100:800);

    % [] Adds a Title to the Third Subplot
    title('Zenith', 'FontSize', 16, 'Parent', Axes3);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes3);

    % [] Adds a Label to the Y Axis
    ylabel('Speed (m/s)', 'FontSize', 12, 'Parent', Axes3);

    % [] Adds a Plot to the Third Subplot
    plot(t, VZ, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes3);

    %% Subplot 4: Total Speed vs. Time

    % [] Adds Fourth Subplot
    Axes4 = subplot(2, 2, 4, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [0, 1000], ...
            'Xtick', 0:7:70, ...
            'Ytick', 0:100:1000);

    % [] Adds a Title to the Fourth Subplot
    title('Relative', 'FontSize', 16, 'Parent', Axes4);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes4);

    % [] Adds a Label to the Y Axis
    ylabel('Speed (m/s)', 'FontSize', 12, 'Parent', Axes4);

    % [] Adds a Plot to the Fourth Subplot
    plot(t, VTotal, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes4);

end
