function PlotAcceleration(t, Acggs, C)

    % [km/s^2] Magnitude of Inertial Acceleration
    acg = sqrt(Acggs(1, :).^2 + Acggs(2, :).^2 + Acggs(3, :).^2);

    % [g's] Convert to g's
    acg_gs = acg / C.g0;

    % [] Initiates a New Window and Adjusts Its Properties
    Window = figure( ...
                'Color', 'w',...
                'Name', 'Inertial Acceleration Analysis', ...
                'NumberTitle', 'Off');

    % [] Adds an Axes to the Specified Window and Adjusts Its Properties
    Axes = axes( ...
            'FontName', 'Arial',...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [0, 20], ...
            'Xtick', 0:7:70, ...
            'Ytick', 0:2:20);

    % [] Adds a Title to the Specified Axes and Adjusts Its Properties
    title('Inertial Acceleration', 'FontSize', 20, 'Parent', Axes);

    % [] Adds a Label to the X Axis and Adjusts Its Properties
    xlabel('Time (s)', 'FontSize', 16, 'Parent', Axes);

    % [] Adds a Label to the Y Axis and Adjusts Its Properties
    ylabel('Acceleration (g''s)', 'FontSize', 16, 'Parent', Axes);

    % [] Adds a Plot to the Specified Axes and Adjusts Its Properties
    plot(t, acg_gs, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes);

end
