function PlotAltitude(t, Rcge_ECEF, C)

    % [m] Calculate Altitude Above Mean Equator for Each Time Step
    numPoints = size(Rcge_ECEF, 2);
    altitude = zeros(1, numPoints);
    for i = 1:numPoints
        rcge = norm(Rcge_ECEF(:, i));
        altitude(i) = (rcge - C.Re) * 1000;
    end

    % [] Initiates a New Window and Adjusts Its Properties
    Window = figure( ...
                'Color', 'w',...
                'Name', 'Altitude Above Mean Equator Analysis', ...
                'NumberTitle', 'Off');

    % [] Adds an Axes to the Specified Window and Adjusts Its Properties
    Axes = axes( ...
            'FontName', 'Arial',...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [0, 6000], ...
            'Xtick', 0:7:70, ...
            'Ytick', 0:600:6000);

    % [] Adds a Title to the Specified Axes and Adjusts Its Properties
    title('Altitude Above Mean Equator', 'FontSize', 20, 'Parent', Axes);

    % [] Adds a Label to the X Axis and Adjusts Its Properties
    xlabel('Time (s)', 'FontSize', 16, 'Parent', Axes);

    % [] Adds a Label to the Y Axis and Adjusts Its Properties
    ylabel('Altitude (m)', 'FontSize', 16, 'Parent', Axes);

    % [] Adds a Plot to the Specified Axes and Adjusts Its Properties
    plot(t, altitude, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes);

end
