function PlotAngles(t, Rcggs, ~)

    % [km] Eastern Position
    E = Rcggs(1, :);

    % [km] Northern Position
    N = Rcggs(2, :);

    % [km] Zenith Position
    Z = Rcggs(3, :);

    % [deg] Azimuth Angle (angle in horizontal plane from North toward East)
    azimuth = rad2deg(atan2(E, N));

    % [km] Slant Range (total distance from ground station)
    slant_range = sqrt(E.^2 + N.^2 + Z.^2);

    % [deg] Elevation Angle (angle above horizontal plane)
    elevation = rad2deg(asin(Z ./ slant_range));

    % [] Initiates a New Window and Adjusts Its Properties
    Window = figure( ...
                'Color', 'w',...
                'Name', 'Angle Analysis', ...
                'NumberTitle', 'Off');

    %% Subplot 1: Azimuth vs. Time

    % [] Adds First Subplot
    Axes1 = subplot(2, 1, 1, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [-180, 180], ...
            'Xtick', 0:7:70, ...
            'Ytick', -180:36:180);

    % [] Adds a Title to the First Subplot
    title('Azimuth', 'FontSize', 16, 'Parent', Axes1);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes1);

    % [] Adds a Label to the Y Axis
    ylabel('Azimuth (°)', 'FontSize', 12, 'Parent', Axes1);

    % [] Adds a Plot to the First Subplot
    plot(t, azimuth, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes1);

    %% Subplot 2: Elevation vs. Time

    % [] Adds Second Subplot
    Axes2 = subplot(2, 1, 2, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [-90, 90], ...
            'Xtick', 0:7:70, ...
            'Ytick', -90:18:90);

    % [] Adds a Title to the Second Subplot
    title('Elevation', 'FontSize', 16, 'Parent', Axes2);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes2);

    % [] Adds a Label to the Y Axis
    ylabel('Elevation (°)', 'FontSize', 12, 'Parent', Axes2);

    % [] Adds a Plot to the Second Subplot
    plot(t, elevation, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes2);

end
