function PlotDynamicPressure(t, DynamicPressure)

    % [kPa] Convert Dynamic Pressure to kPa
    DynamicPressure_kPa = DynamicPressure / 1000;

    % [] Initiates a New Window and Adjusts Its Properties
    Window = figure( ...
                'Color', 'w',...
                'Name', 'Dynamic Pressure Analysis', ...
                'NumberTitle', 'Off');

    % [] Adds an Axes to the Specified Window and Adjusts Its Properties
    Axes = axes( ...
            'FontName', 'Arial',...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [0, 500], ...
            'Xtick', 0:7:70, ...
            'Ytick', 0:50:500);

    % [] Adds a Title to the Specified Axes and Adjusts Its Properties
    title('Dynamic Pressure', 'FontSize', 20, 'Parent', Axes);

    % [] Adds a Label to the X Axis and Adjusts Its Properties
    xlabel('Time (s)', 'FontSize', 16, 'Parent', Axes);

    % [] Adds a Label to the Y Axis and Adjusts Its Properties
    ylabel('Pressure (kPa)', 'FontSize', 16, 'Parent', Axes);

    % [] Adds a Plot to the Specified Axes and Adjusts Its Properties
    plot(t, DynamicPressure_kPa, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes);

end
