function PlotDisplacements(t, Rcggs)

    % [m] Eastern Displacement
    E = Rcggs(1, :) * 1000;

    % [m] Northern Displacement
    N = Rcggs(2, :) * 1000;

    % [m] Zenith Displacement
    Z = Rcggs(3, :) * 1000;

    % [m] Linear Range (Slant Range - Total Straight-Line Distance)
    Range = sqrt(E.^2 + N.^2 + Z.^2);

    % [] Initiates a New Window and Adjusts Its Properties
    Window = figure( ...
                'Color', 'w',...
                'Name', 'Displacement Analysis', ...
                'NumberTitle', 'Off');

    %% Subplot 1: Eastern Displacement vs. Time

    % [] Adds First Subplot
    Axes1 = subplot(2, 2, 1, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [0, 7000], ...
            'Xtick', 0:7:70, ...
            'Ytick', 0:700:7000);

    % [] Adds a Title to the First Subplot
    title('East', 'FontSize', 16, 'Parent', Axes1);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes1);

    % [] Adds a Label to the Y Axis
    ylabel('Displacement (m)', 'FontSize', 12, 'Parent', Axes1);

    % [] Adds a Plot to the First Subplot
    plot(t, E, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes1);

    %% Subplot 2: Northern Displacement vs. Time

    % [] Adds Second Subplot
    Axes2 = subplot(2, 2, 2, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [-2500, 0], ...
            'Xtick', 0:7:70, ...
            'Ytick', -2500:250:0);

    % [] Adds a Title to the Second Subplot
    title('North', 'FontSize', 16, 'Parent', Axes2);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes2);

    % [] Adds a Label to the Y Axis
    ylabel('Displacement (m)', 'FontSize', 12, 'Parent', Axes2);

    % [] Adds a Plot to the Second Subplot
    plot(t, N, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes2);

    %% Subplot 3: Zenith Displacement vs. Time

    % [] Adds Third Subplot
    Axes3 = subplot(2, 2, 3, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [0, 6000], ...
            'Xtick', 0:7:70, ...
            'Ytick', 0:600:6000);

    % [] Adds a Title to the Third Subplot
    title('Zenith', 'FontSize', 16, 'Parent', Axes3);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes3);

    % [] Adds a Label to the Y Axis
    ylabel('Displacement (m)', 'FontSize', 12, 'Parent', Axes3);

    % [] Adds a Plot to the Third Subplot
    plot(t, Z, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes3);

    %% Subplot 4: Range vs. Time

    % [] Adds Fourth Subplot
    Axes4 = subplot(2, 2, 4, ...
            'FontName', 'Arial',...
            'FontSize', 8, ...
            'FontWeight', 'bold', ...
            'NextPlot', 'Add', ...
            'Parent', Window, ...
            'XGrid', 'on', ...
            'Ygrid', 'on', ...
            'xlim', [0, 70], ...
            'ylim', [0, 8000], ...
            'Xtick', 0:7:70, ...
            'Ytick', 0:800:8000);

    % [] Adds a Title to the Fourth Subplot
    title('Linear', 'FontSize', 16, 'Parent', Axes4);

    % [] Adds a Label to the X Axis
    xlabel('Time (s)', 'FontSize', 12, 'Parent', Axes4);

    % [] Adds a Label to the Y Axis
    ylabel('Range (m)', 'FontSize', 12, 'Parent', Axes4);

    % [] Adds a Plot to the Fourth Subplot
    plot(t, Range, ...
        'k-', ...
        'LineWidth', 2, ...
        'Parent', Axes4);

end
